export const GET_PLAYLIST = "[PLAYLIST] GET_PLAYLIST"
export const GET_PLAYLIST_SUCCESS = "[PLAYLIST] GET_PLAYLIST_SUCCESS"
export const GET_PLAYLIST_FAILED = "[PLAYLIST] GET_PLAYLIST_FAILED"

export const PLAY_TRACK = "[PLAYER] PLAY_TRACK"
export const PLAY = "[PLAYER] PLAY"
export const PAUSE = "[PLAYER] PAUSE"